Bootstrap: docker
From: ubuntu:20.04

%post
################################################################################# Append custom content to .bashrc using heredoc
addgroup --system --gid 300 slurmadmin
adduser --system --uid 300 --gid 300 --home /opt/slurm/slurm \
        --shell /bin/false slurmadmin

################################################################################# END DEFINITION OF BASHRC

# Set proxy for the environment
export HTTPS_PROXY="http://www-cache.gwdg.de:3128"
export HTTP_PROXY="http://www-cache.gwdg.de:3128"

# Ensure wget uses the proxy by setting it explicitly in the environment
export http_proxy="http://www-cache.gwdg.de:3128"
export https_proxy="http://www-cache.gwdg.de:3128"

# Set proxy for apt directly in its config file
echo 'Acquire::http::Proxy "http://www-cache.gwdg.de:3128";' > /etc/apt/apt.conf
echo 'Acquire::https::Proxy "http://www-cache.gwdg.de:3128";' >> /etc/apt/apt.conf

# Update and install packages
apt-get -y update
apt-get -y install curl wget


%environment
SHELL=/bin/bash
CONDA_DIR=${CONDA_DIR}
PATH=${PATH}:${LSF_BINDIR}:/cm/local/apps/cuda/libs/current/bin:${CONDA_DIR}/bin
HTTPS_PROXY="http://www-cache.gwdg.de:3128"
HTTP_PROXY="http://www-cache.gwdg.de:3128"
http_proxy="http://www-cache.gwdg.de:3128"
https_proxy="http://www-cache.gwdg.de:3128"