Bootstrap: docker
From: ubuntu:22.04

%post

apt-get -y update
apt-get -y install net-tools
apt-get -y install graphviz libgraphviz-dev
apt-get -y install curl wget

# Install conda and check the md5 sum provided on the download site
export CONDA_DIR=/opt/conda
export PATH=$CONDA_DIR/bin:$PATH
export CONDA_VERSION=23.3.1
export MINICONDA_VERSION=py310_${CONDA_VERSION}-0

cd /tmp && \
wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh
echo "e65ad52d60452ce818869c3309d7964e *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c -
/bin/bash Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR
rm Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh
$CONDA_DIR/bin/conda config --system --prepend channels conda-forge
$CONDA_DIR/bin/conda config --system --set auto_update_conda false
$CONDA_DIR/bin/conda config --system --set show_channel_urls true
$CONDA_DIR/bin/conda install --quiet --yes conda="${CONDA_VERSION}"
conda update --all --quiet --yes
conda clean --all -f --yes


# create env
ENV_NAME="exenv"
conda create --name $ENV_NAME python=3.10 -y
conda activate $ENV_NAME

# install packages
conda install --quiet --yes \
    'notebook=6.5.4' \
    'jupyterhub=4.0.0' \
    'jupyterlab=4.0.0'

conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch -y




%environment

PATH=${PATH}:${LSF_BINDIR}:/cm/local/apps/cuda/libs/current/bin:/opt/conda/bin